# GLOBAL
bind = $mainMod, H, movefocus, l
bind = $mainMod, L, movefocus, r
bind = $mainMod, J, movefocus, d
bind = $mainMod, K, movefocus, u

# DWINDLE LAYOUT


# MONOCLE LAYOUT
bind = $mainMod, BRACKETLEFT, layoutmsg, cyclenext 
bind = $mainMod, BRACKETRIGHT, layoutmsg, cycleprev

# MASTER LAYOUT
bind = $mainMod, MINUS, layoutmsg, mfact -0.02
bind = $mainMod, EQUAL, layoutmsg, mfact +0.02
bind = $mainMod, BACKSPACE, layoutmsg, mfact exact 0.60
bind = $mainMod, M, layoutmsg, swapwithmaster

# SCROLLING LAYOUT
bind = $mainMod, period, layoutmsg, swapcol r
bind = $mainMod, comma, layoutmsg, swapcol l
bind = $mainMod SHIFT, right, layoutmsg, movewindowto r
bind = $mainMod SHIFT, left, layoutmsg, movewindowto l
bind = $mainMod SHIFT, up, layoutmsg, movewindowto u
bind = $mainMod SHIFT, down, layoutmsg, movewindowto d
bind = $mainMod, MINUS, layoutmsg, colresize -0.1
bind = $mainMod, EQUAL, layoutmsg, colresize +0.1
bind = $mainMod, M, layoutmsg, colresize +conf
