# -----------------------------------------------------
# Layouts
# -----------------------------------------------------

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
	# new_status=master
	new_on_top=true
	mfact = 0.60
}

scrolling {
	column_width = 0.5
	fullscreen_on_one_column = true
	follow_focus= true
	focus_fit_method = 1
}

binds {
	workspace_back_and_forth = false
	allow_workspace_cycles = true
	pass_mouse_when_bound = false
}
